# API Testing: World Bank Data

In [25]:
import nasdaqdatalink
import logging
import warnings
#import pandas

def logging_config():
    """
    A simple function to configure the logging globally. This is done because of a behavior common in Jupyter/IPython.
    """
    
    for handler in logging.root.handlers[:]:
        logging.root.removeHandler(handler)
    logging.basicConfig(level=logging.INFO)

logging_config()
with open(".session_api_key", "r") as f:
    api_key = f.read().strip()
    
nasdaqdatalink.ApiConfig.api_key = api_key

def extract(table_code):
    """Extract the data from Nasdaq/Quandl given the table code. See data.nasdaq.com for more information.

    Args:
        table_code (String): Table code from nasdaq. For example, to access the world bank data table, its code is "WB/DATA"

    Returns:
        DataFrame
    """
    # Suppress warnings for page limit exceeded
    warnings.filterwarnings(
    "ignore",
    message="UserWarning:*",
    category=UserWarning,)
    
    logging.info(f"Extracting the data with table code {table_code}")
    
    try:
        data = nasdaqdatalink.get_table(table_code)
        logging.debug("Data successfully extracted.")
    except Exception as e:
        logging.error(f"Error occured: {e}")
        
    return data # DataFrame Format

def extract_meta(meta_code):
    metadata = nasdaqdatalink.get_table(meta_code)
    return metadata
    
data = extract("WB/DATA")
metadata = extract_meta("WB/METADATA")
display(data.tail(20))
display(metadata)

INFO:root:Extracting the data with table code WB/DATA
/home/toni11/.local/share/virtualenvs/AI_Projects-tfkgGnhp/lib/python3.13/site-packages/nasdaqdatalink/get_table.py:38: UserWarning: To request more pages, please set paginate=True in your         nasdaqdatalink.get_table() call. For more information see our documentation:         https://github.com/Nasdaq/data-link-python/blob/main/FOR_ANALYSTS.md#things-to-note
  warnings.warn(Message.WARN_PAGE_LIMIT_EXCEEDED, UserWarning)

,series_id,country_code,country_name,year,value
None,,,,,
9980,VC.IDP.TOCV,UGA,Uganda,2011,30000.0
9981,VC.IDP.TOCV,UGA,Uganda,2010,166000.0
9982,VC.IDP.TOCV,UGA,Uganda,2009,435000.0
9983,VC.IDP.TOCV,TUR,Turkiye,2023,1099000.0
9984,VC.IDP.TOCV,TUR,Turkiye,2022,1099000.0
9985,VC.IDP.TOCV,TUR,Turkiye,2021,1099000.0
9986,VC.IDP.TOCV,TUR,Turkiye,2020,1099000.0
9987,VC.IDP.TOCV,TUR,Turkiye,2019,1099000.0
9988,VC.IDP.TOCV,TUR,Turkiye,2018,1097000.0
9989,VC.IDP.TOCV,TUR,Turkiye,2017,1113000.0
9990,VC.IDP.TOCV,TUR,Turkiye,2016,1108000.0
9991,VC.IDP.TOCV,TUR,Turkiye,2015,954000.0
9992,VC.IDP.TOCV,TUR,Turkiye,2014,954000.0
9993,VC.IDP.TOCV,TUR,Turkiye,2013,954000.0
9994,VC.IDP.TOCV,TUR,Turkiye,2012,1000000.0
9995,VC.IDP.TOCV,TUR,Turkiye,2011,1000000.0
9996,VC.IDP.TOCV,TUR,Turkiye,2010,1000000.0
9997,VC.IDP.TOCV,TUR,Turkiye,2009,1000000.0
9998,VC.IDP.TOCV,TUN,Tunisia,2019,4.0
9999,VC.IDP.TOCV,TSS,Sub-Saharan Africa (IDA & IBRD countries),2023,32420020.0

,series_id,name,description
None,,,
0,VC.PKP.TOTL.UN,"Presence of peace keepers (number of troops, p...",Presence of peacebuilders and peacekeepers are...
1,VC.IHR.PSRC.P5,"Intentional homicides (per 100,000 people)",Intentional homicides are estimates of unlawfu...
2,VC.IHR.PSRC.MA.P5,"Intentional homicides, male (per 100,000 male)","Intentional homicides, male are estimates of u..."
3,VC.IHR.PSRC.FE.P5,"Intentional homicides, female (per 100,000 fem...","Intentional homicides, female are estimates of..."
4,VC.IDP.TOCV,"Internally displaced persons, total displaced ...",Internally displaced persons are defined accor...
...,...,...,...
1479,AG.LND.AGRI.ZS,Agricultural land (% of land area),Agricultural land refers to the share of land ...
1480,AG.LND.AGRI.K2,Agricultural land (sq. km),Agricultural land refers to the share of land ...
1481,AG.CON.FERT.ZS,Fertilizer consumption (kilograms per hectare ...,Fertilizer consumption measures the quantity o...
1482,AG.CON.FERT.PT.ZS,Fertilizer consumption (% of fertilizer produc...,Fertilizer consumption measures the quantity o...
1483,AG.AGR.TRAC.NO,"Agricultural machinery, tractors",Agricultural machinery refers to the number of...

In [ ]:
def transform(data):
    clean_data = data
    
    return clean_data
cleaned_data = transform(data)

In [ ]:
def load(cleaned_data):
    return cleaned_data